#!/usr/bin/env sh

SCRIPT=$(readlink -f "${0}")
# Directory of an absolute path to this script
SCRIPTPATH=$(dirname "${SCRIPT}")

/usr/bin/rm -Rf "${SCRIPTPATH}/.tmp" && /usr/bin/mkdir "${SCRIPTPATH}/.tmp"
/usr/bin/curl -L -O https://github.com/ninia/jep/archive/refs/tags/v4.0.0.tar.gz --output-dir "${SCRIPTPATH}/.tmp/"
/usr/bin/tar -xvf "${SCRIPTPATH}/.tmp/v4.0.0.tar.gz" -C "${SCRIPTPATH}/.tmp/"

# copy c sources
/usr/bin/rsync -uva --include="*.c" "${SCRIPTPATH}/.tmp/jep-4.0.0/src/main/c/Jep/" "${SCRIPTPATH}/jep"
/usr/bin/rsync -uva --include="*.c" "${SCRIPTPATH}/.tmp/jep-4.0.0/src/main/c/Objects/" "${SCRIPTPATH}/jep/objects"
/usr/bin/rsync -uva --include="*.h" "${SCRIPTPATH}/.tmp/jep-4.0.0/src/main/c/Include/" "${SCRIPTPATH}/include"

# remove explicit includes generated by java
/usr/bin/find "${SCRIPTPATH}/jep/python/" -type f -name '*.c' -exec /usr/bin/sed -i 's/^#include "jep_python_.*//g' {} \;
/usr/bin/find "${SCRIPTPATH}/jep/" -type f -name '*.c' -exec /usr/bin/sed -i 's/^#include "jep_.*//g' {} \;

# remove JNI entry point
/usr/bin/sed -i '/^JNIEXPORT jint JNICALL$/,/^}$/d' "${SCRIPTPATH}/jep/jep.c"
/usr/bin/sed -i '/^JNIEXPORT void JNICALL$/,/^}$/d' "${SCRIPTPATH}/jep/jep.c"


# change package name jep.* -> com.dropchop.snakejar.embed
/usr/bin/find "${SCRIPTPATH}/jep/python/" -type f -name '*.c' \
  -exec /usr/bin/sed -i 's/JNICALL Java_jep_python_/JNICALL Java_com_dropchop_snakejar_embed_python_/g' {} \;
/usr/bin/find "${SCRIPTPATH}/jep/" -type f -name '*.c' \
  -exec /usr/bin/sed -i 's/JNICALL Java_jep_/JNICALL Java_com_dropchop_snakejar_embed_/g' {} \;

/usr/bin/sed -i 's/"jep\//"com\/dropchop\/snakejar\/embed\//g' "${SCRIPTPATH}/include/jep_util.h"

# copy java sources
/usr/bin/rsync -uva --include="*.java" "${SCRIPTPATH}/.tmp/jep-4.0.0/src/main/java/jep/" "${SCRIPTPATH}/../java/com/dropchop/snakejar/embed"

# fix java package names
/usr/bin/find "${SCRIPTPATH}/../java/com/dropchop/snakejar/embed" -type f -name '*.java' \
  -exec /usr/bin/sed -i 's/package jep;/package com.dropchop.snakejar.embed;/g' {} \;
/usr/bin/find "${SCRIPTPATH}/../java/com/dropchop/snakejar/embed" -type f -name '*.java' \
  -exec /usr/bin/sed -i 's/package jep\.python;/package com.dropchop.snakejar.embed.python;/g' {} \;

# fix java imports
/usr/bin/find "${SCRIPTPATH}/../java/com/dropchop/snakejar/embed" -type f -name '*.java' \
  -exec /usr/bin/sed -i 's/import jep\./import com.dropchop.snakejar.embed./g' {} \;


/usr/bin/rm -Rf "${SCRIPTPATH}/.tmp"
